# 开发环境
version: '1.0'

services:
  # 1. MySQL数据库服务
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mrs_db_root_password
      MYSQL_DATABASE: mrs_dev
      MYSQL_USER: mrs_user
      MYSQL_PASSWORD: mrs_db_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # 2. Redis缓存服务
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 3. Go应用服务
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/config
      - CONFIG_NAME=app.dev
      - CONFIG_TYPE=yaml
      - DATABASE_USER=mrs_user
      - DATABASE_PASSWORD=mrs_db_password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=mrs_dev
      - REDIS_ADDRESS=redis:6379
      - LOG_OUTPUT_PATH=["stdout", "/app/var/log/app.log"]
      - LOG_ERROR_OUTPUT_PATH=["stderr", "/app/var/log/error.log"]
    volumes:
      - ./config:/app/config
      - ./var/log:/app/var/log
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

# 定义命名的volumes，用于数据持久化
volumes:
  mysql_dev_data:
  redis_dev_data:
